trigger:
- master

jobs:

- job: 'Devops-Testing despliegue continuo'
  pool:
    #vmImage: 'vs2017-win2016'
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install robotframework robotframework-seleniumlibrary && npm install chromedriver
    displayName: 'Instalando dependencias - RobotFramework & ChromeDriver'

  - powershell: robot -d results sistema_notificaciones
    displayName: 'Ejecutando robot Notificaciones obligatorias'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      searchFolder: 'D:\a\1\s\'
      condition: succeededOrFailed()
      displayName: 'Publicando los resultados del test en carpeta results'
